Import('env')

local_env = env.Clone()

# Application sources (relative to application/)
sources = [
    'source/car.c' if env["role"] == "car" else 'source/fob.c',
    'source/messages.c',
    'source/host_msg_helpers.c',
]

if env["role"] == "car":
    sources.append('source/rand.c')

# Build objects only (not a program)
objects = local_env.Object(sources)

Return('objects')