Import('env')

# Clone a clean environment specifically for drivers
driver_env = env.Clone()

# Override any previous optimization flag
# Relies on compiler observing the "last flag wins" rule
driver_env.Append(CPPFLAGS=[
    '-03'
])

driver_sources = Glob('drivers/*.c')

stm32_drivers = driver_env.StaticLibrary(
    target='/stm32_hal',
    source=driver_sources
)

Return('stm32_drivers')