Import('env')

# Clone a clean environment specifically for drivers
local_env = env.Clone()

sources = [
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c',
    'STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c'
]

# Build objects only (not a program)
objects = local_env.Object(sources)

Return('objects')