Import('app_env', 'gen_secrets_action')

x86_env = app_env.Clone()

# x86-specific include paths
x86_env.Append(CPPPATH=[
    '#/hardware/x86/include',
    '#/hardware/x86/ui'
])

# x86 sources
sources = [
    'source/x86.c',
    'source/uart_x86.c',
]

ui = x86_env.get('ui')
if ui:
    sources.append(f"ui/{ui}/{ui}_x86.c")

x86_env.Append(LINKFLAGS = [
    '-Wl,--gc-sections',
    f'-Wl,-Map={x86_env["build_dir"]}/x86.map,--cref'
])

x86_env.Append(LIBS=[
    'm',
    'pthread'
])

secrets_h = x86_env.Command(
    target='secrets.h',
    source=['#secrets/car_secrets.json'],
    action=gen_secrets_action
)

# Build application with our architecture-specific environment
app_objects = SConscript(
    '#/application/SConscript',
    variant_dir='application',  # Relative to current variant_dir
    duplicate=0,
    exports={'env': x86_env}  # Pass our configured environment
)

app = x86_env.Program(f'{x86_env["name"]}', app_objects + sources)
x86_env.Depends(app, secrets_h)

Return('app')