Import('env')

# Clone a clean environment specifically for drivers
local_env = env.Clone()

sources = Glob('tivaware/driverlib/*.c')

# Build objects only (not a program)
objects = local_env.Object(sources)

Return('objects')